services:
  # --- PBU-TUNE FRONTEND ---
  site:
    image: ghcr.io/wiktorszelag/fryzjer-backend-site:latest
    container_name: pbutune_site
    ports:
      - "8090:80"
    restart: always

  # --- FRYZJER APP ---
  fryzjer_app_service: # Nazwa usługi zmieniona, żeby uniknąć myślników w hostach
    image: ghcr.io/wiktorszelag/fryzjer-backend:latest
    container_name: fryzjer_app
    ports:
      - "8084:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fryzjer_db:5432/fryzjer_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - fryzjer_db
    restart: always

  fryzjer_db: # Kluczowe: zmiana z fryzjer-db na fryzjer_db
    image: postgres:15-alpine
    container_name: fryzjer_db
    environment:
      - POSTGRES_DB=fryzjer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - fryzjer_postgres_data:/var/lib/postgresql/data
    restart: always

  # --- ON THE SPOTTED ---
  spotted_app_service:
    image: ghcr.io/wiktorszelag/spotted-app-backend:latest
    container_name: spotted_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spotted_db:5432/spotted_app_db
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - spotted_db
    restart: always

  spotted_db: # Kluczowe: zmiana z spotted-db na spotted_db
    image: postgres:15-alpine
    container_name: spotted_db
    environment:
      - POSTGRES_DB=spotted_app_db
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - spotted_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  fryzjer_postgres_data:
  spotted_postgres_data: